language: node_js

node_js:
  - 12
  - 10

script:
  - npm run test:ci

branches:
  only:
    - master
    - /v\d+\.\d+.+/

deploy:
  skip_cleanup: true
  provider: npm
  email: "talk@selwyn.cc"
  api_key: $NPM_TOKEN
  on:
    branch: master
    tags: true
